Github.Search/Models/GithubResults.cs
using System.Text.Json.Serialization;

namespace Github.Search.Models
{
    public class GithubResults
    {
        public class Repositories
        {
            public int total_count { get; set; }
            public bool incomplete_results { get; set; }
        }

        public class RepCollections
        {
            public int total_count { get; set; }
            public bool incomplete_results { get; set; }

            //private List<Repositories> repositories;

            //public List<Repositories> Repositories { get => this.repositories; set => this.repositories = value; }
        }
    }
}

Github.Search/Controllers/GithubController.cs
using Github.Search.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Github.Search.Controllers
{
    public class GithubController : Controller
    {
        private readonly IGithubService service;

        public GithubController(IGithubService service)
        {
            this.service = service;
        }

        [HttpPost]
        public async Task<IActionResult> Index(IFormCollection form)
        {
            string searchText = form["SearchText"];

            if (searchText != string.Empty)
            {
                var reposList = await service.SearchByStringAsync(searchText);
                return Ok(reposList);
            }

            return NotFound("Empty String");
        }

    }
}

Github.Search/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Github.Search.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Github.Search/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Github.Search.Pages
{
    public class IndexModel : PageModel
    {
        public IndexModel(ILogger<IndexModel> logger)
        {
            //_logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Github.Search/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Github.Search.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Github.Search/Pages/Shared/ShowDetails.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Github.Search.Pages
{
    public class ShowDetailsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Github.Search/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}


@using (Html.BeginForm("Index", "Github", FormMethod.Post))
{
<div class="text-center">
    <h1 class="display-4">Welcome</h1>

    <h2>Github search</h2>
    @Html.TextBox("SearchText", null, new { required = "required" })
    <input type="submit" value="Submit"/>
</div>
}

Github.Search/Pages/Shared/ShowDetails.cshtml
@page
@model Github.Search.Pages.ShowDetailsModel
@{

}


<p>

    Name: @ViewBag.FirstName
</p>

Github.Search/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Github.Search</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Github.Search.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Github.Search</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Github">Github</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Github.Search - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>